# A vscode remote container docker image with conda from
# https://hub.docker.com/_/microsoft-vscode-devcontainers
FROM mcr.microsoft.com/vscode/devcontainers/miniconda:0-3

RUN conda install -c conda-forge fenics

# Possible when FESTIM is open-source 
# RUN pip install FESTIM